In [3]:
import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()
df=pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [9]:
df.head()
df.shape
# df.plot.scatter(x='petal width (cm)' ,y='petal length (cm)',title-'scatterplot');
print(df.corr())
print(df.describe())

                   sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000  
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          

In [10]:
# preprocessing
y=df['petal width (cm)'].values.reshape(-1,1)
x=df['petal length (cm)'].values.reshape(-1,1)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train)
print(y_train)

[[4.1]
 [1.5]
 [4.2]
 [1.2]
 [4.6]
 [5.1]
 [4.4]
 [1.5]
 [1.4]
 [4.2]
 [1.4]
 [3.5]
 [5.6]
 [1.1]
 [4.7]
 [1.6]
 [1.7]
 [4.9]
 [4. ]
 [6.6]
 [1.4]
 [5.6]
 [1.4]
 [1. ]
 [3.9]
 [1.5]
 [4. ]
 [4.5]
 [5.6]
 [1.3]
 [1.5]
 [1.9]
 [5.1]
 [5.5]
 [1.6]
 [5.9]
 [1.5]
 [6.3]
 [5. ]
 [1.5]
 [5.4]
 [3. ]
 [1.4]
 [4.3]
 [6. ]
 [6. ]
 [4.7]
 [5.5]
 [3.3]
 [4.3]
 [4.8]
 [5.1]
 [5.1]
 [6.1]
 [1.6]
 [1.5]
 [4.5]
 [6.1]
 [4.1]
 [5.1]
 [1.7]
 [1.5]
 [6.9]
 [3.6]
 [4.9]
 [5.7]
 [4.9]
 [4.5]
 [4.5]
 [1.7]
 [4.4]
 [4.5]
 [1.5]
 [5.8]
 [1.6]
 [5.3]
 [1.5]
 [4.6]
 [1.6]
 [4.5]
 [1.5]
 [4.7]
 [4.9]
 [5.2]
 [4.6]
 [3.8]
 [1.4]
 [3.9]
 [5.7]
 [1.7]
 [5. ]
 [1.4]
 [3.9]
 [4.9]
 [1.4]
 [5.1]
 [1.3]
 [1.5]
 [5.9]
 [4.7]
 [1.4]
 [4.8]
 [1.3]
 [5. ]
 [5.3]
 [4.8]
 [5.2]
 [5.1]
 [1.6]
 [5. ]
 [6.7]
 [5.5]
 [1.3]
 [1.3]
 [4. ]
 [4.8]
 [4.5]
 [6.1]
 [5.8]
 [4.4]]
[[1.3]
 [0.2]
 [1.5]
 [0.2]
 [1.4]
 [2. ]
 [1.3]
 [0.1]
 [0.2]
 [1.3]
 [0.3]
 [1. ]
 [1.4]
 [0.1]
 [1.2]
 [0.2]
 [0.4]
 [1.5]
 [1.2]
 [2.1]
 [0.2]
 [2.1]
 [0.1

In [14]:
# train the model
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.intercept_)
print(regressor.coef_)

[-0.36507538]
[[0.41676026]]


In [15]:
# prediction
score=regressor.predict([[7.5]])
print(score)

[[2.76062656]]


In [16]:
y_pred=regressor.predict(x_test)
df_pred=pd.DataFrame({'Actual':y_test.squeeze(),'predicted':y_pred.squeeze()})
print(df_pred)

    Actual  predicted
0      1.3   1.301966
1      0.2   0.301741
2      1.8   2.052134
3      2.0   2.302190
4      0.4   0.260065
5      1.0   1.010233
6      0.3   0.176713
7      1.8   1.968782
8      0.3   0.218389
9      0.2   0.218389
10     1.3   1.385318
11     1.9   1.760402
12     2.1   1.885430
13     2.3   2.010458
14     1.0   1.176938
15     1.3   1.301966
16     1.5   1.510346
17     1.3   1.343642
18     2.4   1.968782
19     1.2   1.385318
20     1.0   1.093586
21     2.4   1.968782
22     0.2   0.135037
23     0.2   0.426769
24     1.2   1.468670
25     0.2   0.176713
26     0.3   0.218389
27     0.2   0.218389
28     2.2   2.427218
29     1.5   1.593698


In [20]:
# Evaluating the model
from sklearn.metrics import mean_absolute_error,mean_squared_error
import numpy as np
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse);
print(mae)
print(mse)
print(rmse)

0.14360437709829751
0.03454521901150282
0.18586344183701867


In [1]:
# multiple linear regression 
import pandas as pd
from sklearn import linear_model
from sklearn.datasets import load_iris
data=load_iris()
df=pd.DataFrame(data=data.data,columns=data.feature_names)

In [2]:
y=df['petal width (cm)']
x=df[['petal length (cm)','sepal length (cm)']]

In [3]:
regr=linear_model.LinearRegression()
regr.fit(x,y)
print(regr.coef_)

[ 0.44937611 -0.08221782]


In [4]:
pred=regr.predict([[7.3,5]])
print(pred)

[2.86036056]


C:\Users\Ankit Pandey\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [2]:
# Logistic Regression
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [4]:
x=np.arange(10).reshape(-1,1)
y=np.array([0,1,0,1,0,0,0,1,0,1])
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 0 1 0 0 0 1 0 1]


In [6]:
model =LogisticRegression(solver='liblinear' ,C=10.0 ,random_state=0)
model.fit(x,y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [7]:
print(model.intercept_)
print(model.coef_)

[-0.75565043]
[[0.08361731]]


In [8]:
p_pred = model.predict_proba(x)
y_pred=model.predict(x)
print(p_pred)
print(y_pred)

[[0.68040865 0.31959135]
 [0.66195826 0.33804174]
 [0.64300158 0.35699842]
 [0.62358633 0.37641367]
 [0.60376586 0.39623414]
 [0.58359864 0.41640136]
 [0.56314765 0.43685235]
 [0.54247966 0.45752034]
 [0.52166441 0.47833559]
 [0.50077366 0.49922634]]
[0 0 0 0 0 0 0 0 0 0]


In [9]:
# confusion matrix
conf=confusion_matrix(y,y_pred)
print(conf)

[[6 0]
 [4 0]]


In [10]:
report =classification_report(y,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.60      1.00      0.75         6
           1       0.00      0.00      0.00         4

    accuracy                           0.60        10
   macro avg       0.30      0.50      0.37        10
weighted avg       0.36      0.60      0.45        10



C:\Users\Ankit Pandey\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ankit Pandey\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ankit Pandey\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.